export const categoryMapping: { [key: string]: number } = {
    "Utilities": 1,
    "Electronics & Gadgets": 2,
    "Dining Out & Takeout": 3,
    "Household Items": 4,
    "Groceries": 5,
    "Rent/Mortgage": 6,
    "Transportation & Gas": 7,
    "Clothing & Accessories": 8,
    "Subscriptions & Memberships": 9,
    "Fitness & Health": 10,
    "Leisure & Entertainment": 11,
    "Travel & Vacation": 12,
    "Gifts & Donations": 13,
    "Pet Care": 14,
    "Debt Payments": 15,
    "Taxes & Fees": 16,
    "Personal Care": 17,
    "Medical Healthcare": 18,
    "Education & Learning": 19,
    "Childcare & Kids": 20,
    "Insurance Premiums": 21,
    "Miscellaneous": 22,  // Ensure this is correctly handled
    "Salary & Wages": 23,
    "Freelancing & Contract Work": 24,
    "Business Profits": 25,
    "Investments & Dividends": 28,
    "Rental Income": 29,
    "Bonuses & Commissions": 30,
    "Refunds & Reimbursements": 31,
    "Pension & Retirement Funds": 32,
    "Side Hustle & Part-Time Work": 33,
    "Gifts Received": 26
  };
  