export const categoryMapping: { [key: string]: { id: number; category: 'Needs' | 'Wants' | 'Savings' | 'Income' } } = {
  "Utilities": { id: 1, category: 'Needs' },
  "Electronics & Gadgets": { id: 2, category: 'Wants' },
  "Dining Out & Takeout": { id: 3, category: 'Wants' },
  "Household Items": { id: 4, category: 'Needs' },
  "Groceries": { id: 5, category: 'Needs' },
  "Rent/Mortgage": { id: 6, category: 'Needs' },
  "Transportation & Gas": { id: 7, category: 'Needs' },
  "Clothing & Accessories": { id: 8, category: 'Wants' },
  "Subscriptions & Memberships": { id: 9, category: 'Wants' },
  "Fitness & Health": { id: 10, category: 'Wants' },
  "Leisure & Entertainment": { id: 11, category: 'Wants' },
  "Travel & Vacation": { id: 12, category: 'Wants' },
  "Gifts & Donations": { id: 13, category: 'Wants' },
  "Pet Care": { id: 14, category: 'Needs' },
  "Debt Payments": { id: 15, category: 'Savings' },
  "Taxes & Fees": { id: 16, category: 'Needs' },
  "Personal Care": { id: 17, category: 'Wants' },
  "Medical Healthcare": { id: 18, category: 'Needs' },
  "Education & Learning": { id: 19, category: 'Needs' },
  "Childcare & Kids": { id: 20, category: 'Needs' },
  "Insurance Premiums": { id: 21, category: 'Needs' },
  "Miscellaneous": { id: 22, category: 'Needs' },
  "Salary & Wages": { id: 23, category: 'Income' },
  "Business Profits": { id: 25, category: 'Income' },
  "Rental Income": { id: 29, category: 'Income' },
  "Gifts Received": { id: 26, category: 'Income' },
  "Freelancing & Contract Work": { id: 24, category: 'Income' },
  "Investments & Dividends": { id: 28, category: 'Income' },
  "Bonuses & Commissions": { id: 30, category: 'Income' },
  "Refunds & Reimbursements": { id: 31, category: 'Income' },
  "Pension & Retirement Funds": { id: 32, category: 'Income' },
  "Side Hustle & Part-Time Work": { id: 33, category: 'Income' },
};
